import { supabase } from "../config/supabase.js";

/**
 * Writes a single record to the audit_logs table.
 *
 * @param {object} params
 * @param {string}  params.runId        - simulation_runs.id (required)
 * @param {string}  params.mandateId    - mandates.id (required)
 * @param {string|null} params.attemptId - attempts.id (optional)
 * @param {number}  params.day          - simulation day; 0 is valid (required)
 * @param {string}  params.actor        - component that made the decision (required)
 * @param {string}  params.decisionType - type/label of the decision (required)
 * @param {object}  params.input        - raw input context passed to the actor
 * @param {object}  params.output       - decision output produced by the actor
 * @param {string|null} params.reasoning - optional free-text reasoning
 *
 * @returns {Promise<string>} The inserted audit log row id (generated by PostgreSQL).
 */
export async function logAudit({
  runId,
  mandateId,
  attemptId = null,
  day,
  actor,
  decisionType,
  input = {},
  output = {},
  reasoning = null,
}) {
  if (!runId) {
    throw new Error("runId is required for audit logging");
  }

  if (!mandateId) {
    throw new Error("mandateId is required for audit logging");
  }

  // day === 0 is valid — do NOT use !day here
  if (day === undefined || day === null) {
    throw new Error("day is required for audit logging");
  }

  if (!actor) {
    throw new Error("actor is required for audit logging");
  }

  if (!decisionType) {
    throw new Error("decisionType is required for audit logging");
  }

  const { data, error } = await supabase
    .from("audit_logs")
    .insert({
      run_id: runId,
      mandate_id: mandateId,
      attempt_id: attemptId,
      day,
      actor,
      decision_type: decisionType,
      input,
      output,
      reasoning,
    })
    .select("id")
    .single();

  if (error) {
    throw new Error(`Failed to write audit log: ${error.message}`);
  }

  return data.id;
}
